name: schematiq
description: A hyper-minimal, visually elegant planning assistant.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.4.3+1

  # UI & UX
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  lottie: ^3.1.2
  table_calendar: ^3.1.1
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.6
  pdf: ^3.10.8             # NEW: For PDF generation
  printing: ^5.12.0         # NEW: For saving/sharing the PDF
  share_plus: ^9.0.0       # NEW: For the "Share" functionality
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0      # NEW: For rendering tool logos (if SVG)

  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/